# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/shairport-sync
pkgincludedir = $(includedir)/shairport-sync
pkglibdir = $(libdir)/shairport-sync
pkglibexecdir = $(libexecdir)/shairport-sync
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = shairport-sync$(EXEEXT)
am__append_1 = scripts/shairport-sync.service scripts/shairport-sync.service-avahi scripts/shairport-sync

# include information generated by 'git describe --tags --dirty --broken' if requested
am__append_2 = gitversion.c
am__append_3 = gitversion.c gitversion.h
am__append_4 = $(BUILT_SOURCES)
# Correctly clean the generated headers, but keep the xml description
am__append_5 = $(BUILT_SOURCES)
#am__append_6 = apple_alac.cpp
#am__append_7 = \
#	-DPIDDIR=\"$(CUSTOM_PID_DIR)\"

am__append_8 = mdns_avahi.c
#am__append_9 = mdns_tinysvcmdns.c tinysvcmdns.c
#am__append_10 = mdns_external.c
am__append_11 = audio_alsa.c
#am__append_12 = audio_jack.c
#am__append_13 = audio_sndio.c
#am__append_14 = audio_stdout.c
#am__append_15 = audio_pipe.c
#am__append_16 = audio_dummy.c
#am__append_17 = audio_ao.c
#am__append_18 = audio_soundio.c
#am__append_19 = audio_pa.c
#am__append_20 = audio_pw.c
#am__append_21 = FFTConvolver/AudioFFT.cpp FFTConvolver/FFTConvolver.cpp FFTConvolver/Utilities.cpp FFTConvolver/convolver.cpp
#am__append_22 = -std=c++11
#am__append_23 = mdns_dns_sd.c
am__append_24 = metadata_hub.c
#am__append_25 = mqtt.c
am__append_26 = dacp.c
am__append_27 = lib_tinyhttp.a
am__append_28 = lib_tinyhttp.a
am__append_29 = ptp-utilities.c plist_xml_strings.c
am__append_30 = lib_pair_ap.a
am__append_31 = lib_pair_ap.a
am__append_32 = plist_xml_strings.c plist_xml_strings.h
am__append_33 = $(BUILT_SOURCES)
# Correctly clean the generated headers, but keep the xml description
am__append_34 = $(BUILT_SOURCES)
am__append_35 = lib_dbus_interface.a
am__append_36 = lib_dbus_interface.a
am__append_37 = dbus-service.c
am__append_38 = dbus-interface.h dbus-interface.c
# We don't want to install this header
am__append_39 = $(BUILT_SOURCES)
# Correctly clean the generated headers, but keep the xml description
am__append_40 = $(BUILT_SOURCES)
am__append_41 = lib_mpris_interface.a
am__append_42 = lib_mpris_interface.a
am__append_43 = mpris-service.c
am__append_44 = mpris-interface.h mpris-interface.c
# We don't want to install this header
am__append_45 = $(BUILT_SOURCES)
# Correctly clean the generated headers, but keep the xml description
am__append_46 = $(BUILT_SOURCES)
noinst_PROGRAMS = $(am__EXEEXT_1) $(am__EXEEXT_2)
am__append_47 = shairport-sync-dbus-test-client
am__append_48 = shairport-sync-mpris-test-client
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__noinst_HEADERS_DIST) \
	$(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = scripts/shairport-sync.service-avahi \
	scripts/shairport-sync.service scripts/shairport-sync
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
am__EXEEXT_1 = shairport-sync-dbus-test-client$(EXEEXT)
am__EXEEXT_2 = shairport-sync-mpris-test-client$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)
LIBRARIES = $(noinst_LIBRARIES)
AM_V_AR = $(am__v_AR_$(V))
am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
am__v_AR_0 = @echo "  AR      " $@;
am__v_AR_1 = 
lib_dbus_interface_a_AR = $(AR) $(ARFLAGS)
lib_dbus_interface_a_LIBADD =
am__lib_dbus_interface_a_SOURCES_DIST = dbus-interface.c
am_lib_dbus_interface_a_OBJECTS =  \
	lib_dbus_interface_a-dbus-interface.$(OBJEXT)
lib_dbus_interface_a_OBJECTS = $(am_lib_dbus_interface_a_OBJECTS)
lib_mpris_interface_a_AR = $(AR) $(ARFLAGS)
lib_mpris_interface_a_LIBADD =
am__lib_mpris_interface_a_SOURCES_DIST = mpris-interface.c
am_lib_mpris_interface_a_OBJECTS = lib_mpris_interface_a-mpris-interface.$(OBJEXT)
lib_mpris_interface_a_OBJECTS = $(am_lib_mpris_interface_a_OBJECTS)
lib_pair_ap_a_AR = $(AR) $(ARFLAGS)
lib_pair_ap_a_LIBADD =
am__lib_pair_ap_a_SOURCES_DIST = pair_ap/pair.c pair_ap/pair_fruit.c \
	pair_ap/pair_homekit.c pair_ap/pair-tlv.c
am__dirstamp = $(am__leading_dot)dirstamp
am_lib_pair_ap_a_OBJECTS =  \
	pair_ap/lib_pair_ap_a-pair.$(OBJEXT) \
	pair_ap/lib_pair_ap_a-pair_fruit.$(OBJEXT) \
	pair_ap/lib_pair_ap_a-pair_homekit.$(OBJEXT) \
	pair_ap/lib_pair_ap_a-pair-tlv.$(OBJEXT)
lib_pair_ap_a_OBJECTS = $(am_lib_pair_ap_a_OBJECTS)
lib_tinyhttp_a_AR = $(AR) $(ARFLAGS)
lib_tinyhttp_a_LIBADD =
am__lib_tinyhttp_a_SOURCES_DIST = tinyhttp/chunk.c tinyhttp/header.c \
	tinyhttp/http.c
am_lib_tinyhttp_a_OBJECTS =  \
	tinyhttp/lib_tinyhttp_a-chunk.$(OBJEXT) \
	tinyhttp/lib_tinyhttp_a-header.$(OBJEXT) \
	tinyhttp/lib_tinyhttp_a-http.$(OBJEXT)
lib_tinyhttp_a_OBJECTS = $(am_lib_tinyhttp_a_OBJECTS)
am__shairport_sync_SOURCES_DIST = shairport.c rtsp.c mdns.c common.c \
	rtp.c player.c alac.c audio.c loudness.c activity_monitor.c \
	scripts/shairport-sync.service \
	scripts/shairport-sync.service-avahi scripts/shairport-sync \
	gitversion.c apple_alac.cpp mdns_avahi.c mdns_tinysvcmdns.c \
	tinysvcmdns.c mdns_external.c audio_alsa.c audio_jack.c \
	audio_sndio.c audio_stdout.c audio_pipe.c audio_dummy.c \
	audio_ao.c audio_soundio.c audio_pa.c audio_pw.c \
	FFTConvolver/AudioFFT.cpp FFTConvolver/FFTConvolver.cpp \
	FFTConvolver/Utilities.cpp FFTConvolver/convolver.cpp \
	mdns_dns_sd.c metadata_hub.c mqtt.c dacp.c ptp-utilities.c \
	plist_xml_strings.c dbus-service.c mpris-service.c
am__objects_1 =
am__objects_2 = gitversion.$(OBJEXT)
#am__objects_3 = apple_alac.$(OBJEXT)
am__objects_4 = mdns_avahi.$(OBJEXT)
#am__objects_5 = mdns_tinysvcmdns.$(OBJEXT) \
#	tinysvcmdns.$(OBJEXT)
#am__objects_6 = mdns_external.$(OBJEXT)
am__objects_7 = audio_alsa.$(OBJEXT)
#am__objects_8 = audio_jack.$(OBJEXT)
#am__objects_9 = audio_sndio.$(OBJEXT)
#am__objects_10 = audio_stdout.$(OBJEXT)
#am__objects_11 = audio_pipe.$(OBJEXT)
#am__objects_12 = audio_dummy.$(OBJEXT)
#am__objects_13 = audio_ao.$(OBJEXT)
#am__objects_14 = audio_soundio.$(OBJEXT)
#am__objects_15 = audio_pa.$(OBJEXT)
#am__objects_16 = audio_pw.$(OBJEXT)
#am__objects_17 =  \
#	FFTConvolver/AudioFFT.$(OBJEXT) \
#	FFTConvolver/FFTConvolver.$(OBJEXT) \
#	FFTConvolver/Utilities.$(OBJEXT) \
#	FFTConvolver/convolver.$(OBJEXT)
#am__objects_18 = mdns_dns_sd.$(OBJEXT)
am__objects_19 = metadata_hub.$(OBJEXT)
#am__objects_20 = mqtt.$(OBJEXT)
am__objects_21 = dacp.$(OBJEXT)
am__objects_22 = ptp-utilities.$(OBJEXT) \
	plist_xml_strings.$(OBJEXT)
am__objects_23 = dbus-service.$(OBJEXT)
am__objects_24 = mpris-service.$(OBJEXT)
am_shairport_sync_OBJECTS = shairport.$(OBJEXT) rtsp.$(OBJEXT) \
	mdns.$(OBJEXT) common.$(OBJEXT) rtp.$(OBJEXT) player.$(OBJEXT) \
	alac.$(OBJEXT) audio.$(OBJEXT) loudness.$(OBJEXT) \
	activity_monitor.$(OBJEXT) $(am__objects_1) $(am__objects_2) \
	$(am__objects_3) $(am__objects_4) $(am__objects_5) \
	$(am__objects_6) $(am__objects_7) $(am__objects_8) \
	$(am__objects_9) $(am__objects_10) $(am__objects_11) \
	$(am__objects_12) $(am__objects_13) $(am__objects_14) \
	$(am__objects_15) $(am__objects_16) $(am__objects_17) \
	$(am__objects_18) $(am__objects_19) $(am__objects_20) \
	$(am__objects_21) $(am__objects_22) $(am__objects_23) \
	$(am__objects_24)
shairport_sync_OBJECTS = $(am_shairport_sync_OBJECTS)
shairport_sync_DEPENDENCIES = $(am__append_27) $(am__append_30) \
	$(am__append_35) $(am__append_41)
am__shairport_sync_dbus_test_client_SOURCES_DIST =  \
	shairport-sync-dbus-test-client.c
am_shairport_sync_dbus_test_client_OBJECTS = shairport-sync-dbus-test-client.$(OBJEXT)
shairport_sync_dbus_test_client_OBJECTS =  \
	$(am_shairport_sync_dbus_test_client_OBJECTS)
shairport_sync_dbus_test_client_DEPENDENCIES =  \
	lib_dbus_interface.a
am__shairport_sync_mpris_test_client_SOURCES_DIST =  \
	shairport-sync-mpris-test-client.c
am_shairport_sync_mpris_test_client_OBJECTS = shairport-sync-mpris-test-client.$(OBJEXT)
shairport_sync_mpris_test_client_OBJECTS =  \
	$(am_shairport_sync_mpris_test_client_OBJECTS)
shairport_sync_mpris_test_client_DEPENDENCIES =  \
	lib_mpris_interface.a
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/activity_monitor.Po \
	./$(DEPDIR)/alac.Po ./$(DEPDIR)/apple_alac.Po \
	./$(DEPDIR)/audio.Po ./$(DEPDIR)/audio_alsa.Po \
	./$(DEPDIR)/audio_ao.Po ./$(DEPDIR)/audio_dummy.Po \
	./$(DEPDIR)/audio_jack.Po ./$(DEPDIR)/audio_pa.Po \
	./$(DEPDIR)/audio_pipe.Po ./$(DEPDIR)/audio_pw.Po \
	./$(DEPDIR)/audio_sndio.Po ./$(DEPDIR)/audio_soundio.Po \
	./$(DEPDIR)/audio_stdout.Po ./$(DEPDIR)/common.Po \
	./$(DEPDIR)/dacp.Po ./$(DEPDIR)/dbus-service.Po \
	./$(DEPDIR)/gitversion.Po \
	./$(DEPDIR)/lib_dbus_interface_a-dbus-interface.Po \
	./$(DEPDIR)/lib_mpris_interface_a-mpris-interface.Po \
	./$(DEPDIR)/loudness.Po ./$(DEPDIR)/mdns.Po \
	./$(DEPDIR)/mdns_avahi.Po ./$(DEPDIR)/mdns_dns_sd.Po \
	./$(DEPDIR)/mdns_external.Po ./$(DEPDIR)/mdns_tinysvcmdns.Po \
	./$(DEPDIR)/metadata_hub.Po ./$(DEPDIR)/mpris-service.Po \
	./$(DEPDIR)/mqtt.Po ./$(DEPDIR)/player.Po \
	./$(DEPDIR)/plist_xml_strings.Po ./$(DEPDIR)/ptp-utilities.Po \
	./$(DEPDIR)/rtp.Po ./$(DEPDIR)/rtsp.Po \
	./$(DEPDIR)/shairport-sync-dbus-test-client.Po \
	./$(DEPDIR)/shairport-sync-mpris-test-client.Po \
	./$(DEPDIR)/shairport.Po ./$(DEPDIR)/tinysvcmdns.Po \
	FFTConvolver/$(DEPDIR)/AudioFFT.Po \
	FFTConvolver/$(DEPDIR)/FFTConvolver.Po \
	FFTConvolver/$(DEPDIR)/Utilities.Po \
	FFTConvolver/$(DEPDIR)/convolver.Po \
	pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Po \
	pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Po \
	pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Po \
	pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Po \
	tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Po \
	tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Po \
	tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(lib_dbus_interface_a_SOURCES) \
	$(lib_mpris_interface_a_SOURCES) $(lib_pair_ap_a_SOURCES) \
	$(lib_tinyhttp_a_SOURCES) $(shairport_sync_SOURCES) \
	$(shairport_sync_dbus_test_client_SOURCES) \
	$(shairport_sync_mpris_test_client_SOURCES)
DIST_SOURCES = $(am__lib_dbus_interface_a_SOURCES_DIST) \
	$(am__lib_mpris_interface_a_SOURCES_DIST) \
	$(am__lib_pair_ap_a_SOURCES_DIST) \
	$(am__lib_tinyhttp_a_SOURCES_DIST) \
	$(am__shairport_sync_SOURCES_DIST) \
	$(am__shairport_sync_dbus_test_client_SOURCES_DIST) \
	$(am__shairport_sync_mpris_test_client_SOURCES_DIST)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(man_MANS)
am__noinst_HEADERS_DIST = gitversion.c gitversion.h \
	plist_xml_strings.c plist_xml_strings.h dbus-interface.h \
	dbus-interface.c mpris-interface.h mpris-interface.c
HEADERS = $(noinst_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/scripts/shairport-sync.in \
	$(top_srcdir)/scripts/shairport-sync.service-avahi.in \
	$(top_srcdir)/scripts/shairport-sync.service.in AUTHORS \
	COPYING ChangeLog INSTALL NEWS README compile depcomp \
	install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/volumio/shairport-sync/missing aclocal-1.16
ALLOCA = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AO_CFLAGS = 
AO_LIBS = 
AR = ar
AUTOCONF = ${SHELL} /home/volumio/shairport-sync/missing autoconf
AUTOHEADER = ${SHELL} /home/volumio/shairport-sync/missing autoheader
AUTOMAKE = ${SHELL} /home/volumio/shairport-sync/missing automake-1.16
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -I/usr/include/uuid -I/usr/include/arm-linux-gnueabihf -I/usr/include/arm-linux-gnueabihf -I/usr/include/arm-linux-gnueabihf -I/usr/include/arm-linux-gnueabihf   -pthread -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include    -g -O2
CPP = gcc -E
CPPFLAGS = 
CUSTOM_PID_DIR = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DAEMON_CFLAGS = -D_REENTRANT
DAEMON_LIBS = -ldaemon
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GIT = git
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -luuid -lswresample -lavformat -lavcodec -lavutil -lgcrypt -lsodium -lplist -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lasound -lavahi-common -lavahi-client -lsoxr -lssl -lcrypto -ldaemon -lconfig -lpopt -lm -lpthread -lrt 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/volumio/shairport-sync/missing makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = shairport-sync
PACKAGE_BUGREPORT = 4265913+mikebrady@users.noreply.github.com
PACKAGE_NAME = shairport-sync
PACKAGE_STRING = shairport-sync 4.3.7
PACKAGE_TARNAME = shairport-sync
PACKAGE_URL = 
PACKAGE_VERSION = 4.3.7
PATH_SEPARATOR = :
PIPEWIRE_CFLAGS = 
PIPEWIRE_LIBS = 
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
PULSEAUDIO_CFLAGS = 
PULSEAUDIO_LIBS = 
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
SSL_CFLAGS = 
SSL_LIBS = -lssl -lcrypto
STRIP = 
VERSION = 4.3.7
XXD_CHECK = yes
abs_builddir = /home/volumio/shairport-sync
abs_srcdir = /home/volumio/shairport-sync
abs_top_builddir = /home/volumio/shairport-sync
abs_top_srcdir = /home/volumio/shairport-sync
ac_ct_CC = gcc
ac_ct_CXX = g++
alac_CFLAGS = 
alac_LIBS = 
alsa_CFLAGS = -I/usr/include/alsa
alsa_LIBS = -lasound
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
glib_CFLAGS = -pthread -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include
glib_LIBS = -lgio-2.0 -lgobject-2.0 -lglib-2.0
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/volumio/shairport-sync/install-sh
jack_CFLAGS = 
jack_LIBS = 
libavcodec_CFLAGS = -I/usr/include/arm-linux-gnueabihf
libavcodec_LIBS = -lavcodec
libavformat_CFLAGS = -I/usr/include/arm-linux-gnueabihf
libavformat_LIBS = -lavformat
libavutil_CFLAGS = -I/usr/include/arm-linux-gnueabihf
libavutil_LIBS = -lavutil
libconfig_CFLAGS = 
libconfig_LIBS = -lconfig
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
libgcrypt_CFLAGS = 
libgcrypt_LIBS = 
libplist_CFLAGS = 
libplist_LIBS = -lplist
libsodium_CFLAGS = 
libsodium_LIBS = -lsodium
libswresample_CFLAGS = -I/usr/include/arm-linux-gnueabihf
libswresample_LIBS = -lswresample
libuuid_CFLAGS = -I/usr/include/uuid
libuuid_LIBS = -luuid
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
popt_CFLAGS = 
popt_LIBS = -lpopt
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sndfile_CFLAGS = 
sndfile_LIBS = 
soxr_CFLAGS = 
soxr_LIBS = -lsoxr
srcdir = .
sysconfdir = /etc
systemdsystemunitdir = /lib/systemd/system
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ARFLAGS = cr
man_MANS = $(top_srcdir)/man/shairport-sync.1
lib_pair_ap_a_CFLAGS = -Wall -g -DCONFIG_GCRYPT -pthread
lib_tinyhttp_a_CFLAGS = -pthread
lib_dbus_interface_a_CFLAGS = -pthread
lib_mpris_interface_a_CFLAGS = -pthread
BUILT_SOURCES = $(am__append_3) $(am__append_32) $(am__append_38) \
	$(am__append_44)
noinst_HEADERS = $(am__append_4) $(am__append_33) $(am__append_39) \
	$(am__append_45)
CLEANFILES = $(am__append_5) $(am__append_34) $(am__append_40) \
	$(am__append_46)
shairport_sync_LDADD = $(am__append_27) $(am__append_30) \
	$(am__append_35) $(am__append_41)
noinst_LIBRARIES = $(am__append_28) $(am__append_31) $(am__append_36) \
	$(am__append_42)

# See below for the flags for the test client program
shairport_sync_SOURCES = shairport.c rtsp.c mdns.c common.c rtp.c \
	player.c alac.c audio.c loudness.c activity_monitor.c \
	$(am__append_1) $(am__append_2) $(am__append_6) \
	$(am__append_8) $(am__append_9) $(am__append_10) \
	$(am__append_11) $(am__append_12) $(am__append_13) \
	$(am__append_14) $(am__append_15) $(am__append_16) \
	$(am__append_17) $(am__append_18) $(am__append_19) \
	$(am__append_20) $(am__append_21) $(am__append_23) \
	$(am__append_24) $(am__append_25) $(am__append_26) \
	$(am__append_29) $(am__append_37) $(am__append_43)
AM_CXXFLAGS = -fno-common \
	-Wno-multichar \
	-Wall \
	-Wextra \
	-Wno-clobbered \
	-Wno-psabi \
	-pthread \
	-DSYSCONFDIR=\"$(sysconfdir)\" \
	$(am__append_22)
#AM_CXXFLAGS = -I/usr/local/include \
#	-Wno-multichar \
#	-Wall \
#	-Wextra \
#	-Wno-clobbered \
#	-Wno-psabi \
#	-pthread \
#	-DSYSCONFDIR=\"$(sysconfdir)\" \
#	$(am__append_22)
#AM_CXXFLAGS = -I/usr/local/include \
#	-Wno-multichar \
#	-Wall -Wextra \
#	-pthread \
#	-DSYSCONFDIR=\"$(sysconfdir)\" \
#	$(am__append_22)
#AM_CXXFLAGS = -I/usr/local/include \
#	-Wno-multichar -Wall -Wextra \
#	-Wno-deprecated-declarations -pthread \
#	-DSYSCONFDIR=\"$(sysconfdir)\" \
#	$(am__append_22)
AM_CFLAGS = -fno-common \
	-Wno-multichar \
	-Wall \
	-Wextra \
	-Wno-clobbered \
	-Wno-psabi \
	-pthread \
	-DSYSCONFDIR=\"$(sysconfdir)\" \
	$(am__append_7)
#AM_CFLAGS = -Wno-multichar \
#	-Wall \
#	-Wextra \
#	-pthread \
#	-DSYSCONFDIR=\"$(sysconfdir)\" \
#	$(am__append_7)
#AM_CFLAGS = -Wno-multichar \
#	-Wall -Wextra \
#	-pthread \
#	-DSYSCONFDIR=\"$(sysconfdir)\" \
#	$(am__append_7)
#AM_CFLAGS = -Wno-multichar -Wall -Wextra \
#	-Wno-deprecated-declarations -pthread \
#	-DSYSCONFDIR=\"$(sysconfdir)\" \
#	$(am__append_7)
lib_tinyhttp_a_SOURCES = tinyhttp/chunk.c tinyhttp/header.c tinyhttp/http.c
lib_pair_ap_a_SOURCES = pair_ap/pair.c pair_ap/pair_fruit.c pair_ap/pair_homekit.c pair_ap/pair-tlv.c
lib_dbus_interface_a_SOURCES = dbus-interface.c
lib_mpris_interface_a_SOURCES = mpris-interface.c
shairport_sync_dbus_test_client_SOURCES = shairport-sync-dbus-test-client.c
shairport_sync_dbus_test_client_LDADD = lib_dbus_interface.a
shairport_sync_mpris_test_client_SOURCES = shairport-sync-mpris-test-client.c
shairport_sync_mpris_test_client_LDADD = lib_mpris_interface.a
CONFIG_FILE_INSTALL_TARGET = config-file-install-local
#DBUS_POLICY_DIR = $(sysconfdir)/dbus-1/system.d
DBUS_POLICY_DIR = /etc/dbus-1/system.d
DBUS_POLICY_FILE = scripts/shairport-sync-dbus-policy.conf
#DBUS_POLICY_FILE = scripts/shairport-sync-dbus-policy-cygwin.conf
DBUS_POLICY_INSTALL_TARGET = dbus-policy-install-local
MPRIS_POLICY_FILE = scripts/shairport-sync-mpris-policy.conf
#MPRIS_POLICY_FILE = scripts/shairport-sync-mpris-policy-cygwin.conf
MPRIS_POLICY_INSTALL_TARGET = mpris-policy-install-local
INSTALL_GROUP_TARGET = install-group-local
#INSTALL_USER_TARGET = 
INSTALL_USER_TARGET = install-user-local
#INSTALL_SYSTEMV_TARGET = install-systemv-local
#SYSTEMD_SERVICE = shairport-sync.service
SYSTEMD_SERVICE = shairport-sync.service-avahi
INSTALL_SYSTEMD_TARGET = install-systemd-local
#INSTALL_FREEBSD_TARGET = install-freebsd-local
#INSTALL_CYGWIN_TARGET = install-cygwin-local
all: $(BUILT_SOURCES) config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
scripts/shairport-sync.service-avahi: $(top_builddir)/config.status $(top_srcdir)/scripts/shairport-sync.service-avahi.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/shairport-sync.service: $(top_builddir)/config.status $(top_srcdir)/scripts/shairport-sync.service.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
scripts/shairport-sync: $(top_builddir)/config.status $(top_srcdir)/scripts/shairport-sync.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)

lib_dbus_interface.a: $(lib_dbus_interface_a_OBJECTS) $(lib_dbus_interface_a_DEPENDENCIES) $(EXTRA_lib_dbus_interface_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f lib_dbus_interface.a
	$(AM_V_AR)$(lib_dbus_interface_a_AR) lib_dbus_interface.a $(lib_dbus_interface_a_OBJECTS) $(lib_dbus_interface_a_LIBADD)
	$(AM_V_at)$(RANLIB) lib_dbus_interface.a

lib_mpris_interface.a: $(lib_mpris_interface_a_OBJECTS) $(lib_mpris_interface_a_DEPENDENCIES) $(EXTRA_lib_mpris_interface_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f lib_mpris_interface.a
	$(AM_V_AR)$(lib_mpris_interface_a_AR) lib_mpris_interface.a $(lib_mpris_interface_a_OBJECTS) $(lib_mpris_interface_a_LIBADD)
	$(AM_V_at)$(RANLIB) lib_mpris_interface.a
pair_ap/$(am__dirstamp):
	@$(MKDIR_P) pair_ap
	@: > pair_ap/$(am__dirstamp)
pair_ap/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) pair_ap/$(DEPDIR)
	@: > pair_ap/$(DEPDIR)/$(am__dirstamp)
pair_ap/lib_pair_ap_a-pair.$(OBJEXT): pair_ap/$(am__dirstamp) \
	pair_ap/$(DEPDIR)/$(am__dirstamp)
pair_ap/lib_pair_ap_a-pair_fruit.$(OBJEXT): pair_ap/$(am__dirstamp) \
	pair_ap/$(DEPDIR)/$(am__dirstamp)
pair_ap/lib_pair_ap_a-pair_homekit.$(OBJEXT): pair_ap/$(am__dirstamp) \
	pair_ap/$(DEPDIR)/$(am__dirstamp)
pair_ap/lib_pair_ap_a-pair-tlv.$(OBJEXT): pair_ap/$(am__dirstamp) \
	pair_ap/$(DEPDIR)/$(am__dirstamp)

lib_pair_ap.a: $(lib_pair_ap_a_OBJECTS) $(lib_pair_ap_a_DEPENDENCIES) $(EXTRA_lib_pair_ap_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f lib_pair_ap.a
	$(AM_V_AR)$(lib_pair_ap_a_AR) lib_pair_ap.a $(lib_pair_ap_a_OBJECTS) $(lib_pair_ap_a_LIBADD)
	$(AM_V_at)$(RANLIB) lib_pair_ap.a
tinyhttp/$(am__dirstamp):
	@$(MKDIR_P) tinyhttp
	@: > tinyhttp/$(am__dirstamp)
tinyhttp/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) tinyhttp/$(DEPDIR)
	@: > tinyhttp/$(DEPDIR)/$(am__dirstamp)
tinyhttp/lib_tinyhttp_a-chunk.$(OBJEXT): tinyhttp/$(am__dirstamp) \
	tinyhttp/$(DEPDIR)/$(am__dirstamp)
tinyhttp/lib_tinyhttp_a-header.$(OBJEXT): tinyhttp/$(am__dirstamp) \
	tinyhttp/$(DEPDIR)/$(am__dirstamp)
tinyhttp/lib_tinyhttp_a-http.$(OBJEXT): tinyhttp/$(am__dirstamp) \
	tinyhttp/$(DEPDIR)/$(am__dirstamp)

lib_tinyhttp.a: $(lib_tinyhttp_a_OBJECTS) $(lib_tinyhttp_a_DEPENDENCIES) $(EXTRA_lib_tinyhttp_a_DEPENDENCIES) 
	$(AM_V_at)-rm -f lib_tinyhttp.a
	$(AM_V_AR)$(lib_tinyhttp_a_AR) lib_tinyhttp.a $(lib_tinyhttp_a_OBJECTS) $(lib_tinyhttp_a_LIBADD)
	$(AM_V_at)$(RANLIB) lib_tinyhttp.a
FFTConvolver/$(am__dirstamp):
	@$(MKDIR_P) FFTConvolver
	@: > FFTConvolver/$(am__dirstamp)
FFTConvolver/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) FFTConvolver/$(DEPDIR)
	@: > FFTConvolver/$(DEPDIR)/$(am__dirstamp)
FFTConvolver/AudioFFT.$(OBJEXT): FFTConvolver/$(am__dirstamp) \
	FFTConvolver/$(DEPDIR)/$(am__dirstamp)
FFTConvolver/FFTConvolver.$(OBJEXT): FFTConvolver/$(am__dirstamp) \
	FFTConvolver/$(DEPDIR)/$(am__dirstamp)
FFTConvolver/Utilities.$(OBJEXT): FFTConvolver/$(am__dirstamp) \
	FFTConvolver/$(DEPDIR)/$(am__dirstamp)
FFTConvolver/convolver.$(OBJEXT): FFTConvolver/$(am__dirstamp) \
	FFTConvolver/$(DEPDIR)/$(am__dirstamp)

shairport-sync$(EXEEXT): $(shairport_sync_OBJECTS) $(shairport_sync_DEPENDENCIES) $(EXTRA_shairport_sync_DEPENDENCIES) 
	@rm -f shairport-sync$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(shairport_sync_OBJECTS) $(shairport_sync_LDADD) $(LIBS)

shairport-sync-dbus-test-client$(EXEEXT): $(shairport_sync_dbus_test_client_OBJECTS) $(shairport_sync_dbus_test_client_DEPENDENCIES) $(EXTRA_shairport_sync_dbus_test_client_DEPENDENCIES) 
	@rm -f shairport-sync-dbus-test-client$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(shairport_sync_dbus_test_client_OBJECTS) $(shairport_sync_dbus_test_client_LDADD) $(LIBS)

shairport-sync-mpris-test-client$(EXEEXT): $(shairport_sync_mpris_test_client_OBJECTS) $(shairport_sync_mpris_test_client_DEPENDENCIES) $(EXTRA_shairport_sync_mpris_test_client_DEPENDENCIES) 
	@rm -f shairport-sync-mpris-test-client$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(shairport_sync_mpris_test_client_OBJECTS) $(shairport_sync_mpris_test_client_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f FFTConvolver/*.$(OBJEXT)
	-rm -f pair_ap/*.$(OBJEXT)
	-rm -f tinyhttp/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/activity_monitor.Po # am--include-marker
include ./$(DEPDIR)/alac.Po # am--include-marker
include ./$(DEPDIR)/apple_alac.Po # am--include-marker
include ./$(DEPDIR)/audio.Po # am--include-marker
include ./$(DEPDIR)/audio_alsa.Po # am--include-marker
include ./$(DEPDIR)/audio_ao.Po # am--include-marker
include ./$(DEPDIR)/audio_dummy.Po # am--include-marker
include ./$(DEPDIR)/audio_jack.Po # am--include-marker
include ./$(DEPDIR)/audio_pa.Po # am--include-marker
include ./$(DEPDIR)/audio_pipe.Po # am--include-marker
include ./$(DEPDIR)/audio_pw.Po # am--include-marker
include ./$(DEPDIR)/audio_sndio.Po # am--include-marker
include ./$(DEPDIR)/audio_soundio.Po # am--include-marker
include ./$(DEPDIR)/audio_stdout.Po # am--include-marker
include ./$(DEPDIR)/common.Po # am--include-marker
include ./$(DEPDIR)/dacp.Po # am--include-marker
include ./$(DEPDIR)/dbus-service.Po # am--include-marker
include ./$(DEPDIR)/gitversion.Po # am--include-marker
include ./$(DEPDIR)/lib_dbus_interface_a-dbus-interface.Po # am--include-marker
include ./$(DEPDIR)/lib_mpris_interface_a-mpris-interface.Po # am--include-marker
include ./$(DEPDIR)/loudness.Po # am--include-marker
include ./$(DEPDIR)/mdns.Po # am--include-marker
include ./$(DEPDIR)/mdns_avahi.Po # am--include-marker
include ./$(DEPDIR)/mdns_dns_sd.Po # am--include-marker
include ./$(DEPDIR)/mdns_external.Po # am--include-marker
include ./$(DEPDIR)/mdns_tinysvcmdns.Po # am--include-marker
include ./$(DEPDIR)/metadata_hub.Po # am--include-marker
include ./$(DEPDIR)/mpris-service.Po # am--include-marker
include ./$(DEPDIR)/mqtt.Po # am--include-marker
include ./$(DEPDIR)/player.Po # am--include-marker
include ./$(DEPDIR)/plist_xml_strings.Po # am--include-marker
include ./$(DEPDIR)/ptp-utilities.Po # am--include-marker
include ./$(DEPDIR)/rtp.Po # am--include-marker
include ./$(DEPDIR)/rtsp.Po # am--include-marker
include ./$(DEPDIR)/shairport-sync-dbus-test-client.Po # am--include-marker
include ./$(DEPDIR)/shairport-sync-mpris-test-client.Po # am--include-marker
include ./$(DEPDIR)/shairport.Po # am--include-marker
include ./$(DEPDIR)/tinysvcmdns.Po # am--include-marker
include FFTConvolver/$(DEPDIR)/AudioFFT.Po # am--include-marker
include FFTConvolver/$(DEPDIR)/FFTConvolver.Po # am--include-marker
include FFTConvolver/$(DEPDIR)/Utilities.Po # am--include-marker
include FFTConvolver/$(DEPDIR)/convolver.Po # am--include-marker
include pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Po # am--include-marker
include pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Po # am--include-marker
include pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Po # am--include-marker
include pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Po # am--include-marker
include tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Po # am--include-marker
include tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Po # am--include-marker
include tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

lib_dbus_interface_a-dbus-interface.o: dbus-interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_dbus_interface_a_CFLAGS) $(CFLAGS) -MT lib_dbus_interface_a-dbus-interface.o -MD -MP -MF $(DEPDIR)/lib_dbus_interface_a-dbus-interface.Tpo -c -o lib_dbus_interface_a-dbus-interface.o `test -f 'dbus-interface.c' || echo '$(srcdir)/'`dbus-interface.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/lib_dbus_interface_a-dbus-interface.Tpo $(DEPDIR)/lib_dbus_interface_a-dbus-interface.Po
#	$(AM_V_CC)source='dbus-interface.c' object='lib_dbus_interface_a-dbus-interface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_dbus_interface_a_CFLAGS) $(CFLAGS) -c -o lib_dbus_interface_a-dbus-interface.o `test -f 'dbus-interface.c' || echo '$(srcdir)/'`dbus-interface.c

lib_dbus_interface_a-dbus-interface.obj: dbus-interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_dbus_interface_a_CFLAGS) $(CFLAGS) -MT lib_dbus_interface_a-dbus-interface.obj -MD -MP -MF $(DEPDIR)/lib_dbus_interface_a-dbus-interface.Tpo -c -o lib_dbus_interface_a-dbus-interface.obj `if test -f 'dbus-interface.c'; then $(CYGPATH_W) 'dbus-interface.c'; else $(CYGPATH_W) '$(srcdir)/dbus-interface.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/lib_dbus_interface_a-dbus-interface.Tpo $(DEPDIR)/lib_dbus_interface_a-dbus-interface.Po
#	$(AM_V_CC)source='dbus-interface.c' object='lib_dbus_interface_a-dbus-interface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_dbus_interface_a_CFLAGS) $(CFLAGS) -c -o lib_dbus_interface_a-dbus-interface.obj `if test -f 'dbus-interface.c'; then $(CYGPATH_W) 'dbus-interface.c'; else $(CYGPATH_W) '$(srcdir)/dbus-interface.c'; fi`

lib_mpris_interface_a-mpris-interface.o: mpris-interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_mpris_interface_a_CFLAGS) $(CFLAGS) -MT lib_mpris_interface_a-mpris-interface.o -MD -MP -MF $(DEPDIR)/lib_mpris_interface_a-mpris-interface.Tpo -c -o lib_mpris_interface_a-mpris-interface.o `test -f 'mpris-interface.c' || echo '$(srcdir)/'`mpris-interface.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/lib_mpris_interface_a-mpris-interface.Tpo $(DEPDIR)/lib_mpris_interface_a-mpris-interface.Po
#	$(AM_V_CC)source='mpris-interface.c' object='lib_mpris_interface_a-mpris-interface.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_mpris_interface_a_CFLAGS) $(CFLAGS) -c -o lib_mpris_interface_a-mpris-interface.o `test -f 'mpris-interface.c' || echo '$(srcdir)/'`mpris-interface.c

lib_mpris_interface_a-mpris-interface.obj: mpris-interface.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_mpris_interface_a_CFLAGS) $(CFLAGS) -MT lib_mpris_interface_a-mpris-interface.obj -MD -MP -MF $(DEPDIR)/lib_mpris_interface_a-mpris-interface.Tpo -c -o lib_mpris_interface_a-mpris-interface.obj `if test -f 'mpris-interface.c'; then $(CYGPATH_W) 'mpris-interface.c'; else $(CYGPATH_W) '$(srcdir)/mpris-interface.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/lib_mpris_interface_a-mpris-interface.Tpo $(DEPDIR)/lib_mpris_interface_a-mpris-interface.Po
#	$(AM_V_CC)source='mpris-interface.c' object='lib_mpris_interface_a-mpris-interface.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_mpris_interface_a_CFLAGS) $(CFLAGS) -c -o lib_mpris_interface_a-mpris-interface.obj `if test -f 'mpris-interface.c'; then $(CYGPATH_W) 'mpris-interface.c'; else $(CYGPATH_W) '$(srcdir)/mpris-interface.c'; fi`

pair_ap/lib_pair_ap_a-pair.o: pair_ap/pair.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -MT pair_ap/lib_pair_ap_a-pair.o -MD -MP -MF pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Tpo -c -o pair_ap/lib_pair_ap_a-pair.o `test -f 'pair_ap/pair.c' || echo '$(srcdir)/'`pair_ap/pair.c
	$(AM_V_at)$(am__mv) pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Tpo pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Po
#	$(AM_V_CC)source='pair_ap/pair.c' object='pair_ap/lib_pair_ap_a-pair.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -c -o pair_ap/lib_pair_ap_a-pair.o `test -f 'pair_ap/pair.c' || echo '$(srcdir)/'`pair_ap/pair.c

pair_ap/lib_pair_ap_a-pair.obj: pair_ap/pair.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -MT pair_ap/lib_pair_ap_a-pair.obj -MD -MP -MF pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Tpo -c -o pair_ap/lib_pair_ap_a-pair.obj `if test -f 'pair_ap/pair.c'; then $(CYGPATH_W) 'pair_ap/pair.c'; else $(CYGPATH_W) '$(srcdir)/pair_ap/pair.c'; fi`
	$(AM_V_at)$(am__mv) pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Tpo pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Po
#	$(AM_V_CC)source='pair_ap/pair.c' object='pair_ap/lib_pair_ap_a-pair.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -c -o pair_ap/lib_pair_ap_a-pair.obj `if test -f 'pair_ap/pair.c'; then $(CYGPATH_W) 'pair_ap/pair.c'; else $(CYGPATH_W) '$(srcdir)/pair_ap/pair.c'; fi`

pair_ap/lib_pair_ap_a-pair_fruit.o: pair_ap/pair_fruit.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -MT pair_ap/lib_pair_ap_a-pair_fruit.o -MD -MP -MF pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Tpo -c -o pair_ap/lib_pair_ap_a-pair_fruit.o `test -f 'pair_ap/pair_fruit.c' || echo '$(srcdir)/'`pair_ap/pair_fruit.c
	$(AM_V_at)$(am__mv) pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Tpo pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Po
#	$(AM_V_CC)source='pair_ap/pair_fruit.c' object='pair_ap/lib_pair_ap_a-pair_fruit.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -c -o pair_ap/lib_pair_ap_a-pair_fruit.o `test -f 'pair_ap/pair_fruit.c' || echo '$(srcdir)/'`pair_ap/pair_fruit.c

pair_ap/lib_pair_ap_a-pair_fruit.obj: pair_ap/pair_fruit.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -MT pair_ap/lib_pair_ap_a-pair_fruit.obj -MD -MP -MF pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Tpo -c -o pair_ap/lib_pair_ap_a-pair_fruit.obj `if test -f 'pair_ap/pair_fruit.c'; then $(CYGPATH_W) 'pair_ap/pair_fruit.c'; else $(CYGPATH_W) '$(srcdir)/pair_ap/pair_fruit.c'; fi`
	$(AM_V_at)$(am__mv) pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Tpo pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Po
#	$(AM_V_CC)source='pair_ap/pair_fruit.c' object='pair_ap/lib_pair_ap_a-pair_fruit.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -c -o pair_ap/lib_pair_ap_a-pair_fruit.obj `if test -f 'pair_ap/pair_fruit.c'; then $(CYGPATH_W) 'pair_ap/pair_fruit.c'; else $(CYGPATH_W) '$(srcdir)/pair_ap/pair_fruit.c'; fi`

pair_ap/lib_pair_ap_a-pair_homekit.o: pair_ap/pair_homekit.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -MT pair_ap/lib_pair_ap_a-pair_homekit.o -MD -MP -MF pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Tpo -c -o pair_ap/lib_pair_ap_a-pair_homekit.o `test -f 'pair_ap/pair_homekit.c' || echo '$(srcdir)/'`pair_ap/pair_homekit.c
	$(AM_V_at)$(am__mv) pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Tpo pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Po
#	$(AM_V_CC)source='pair_ap/pair_homekit.c' object='pair_ap/lib_pair_ap_a-pair_homekit.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -c -o pair_ap/lib_pair_ap_a-pair_homekit.o `test -f 'pair_ap/pair_homekit.c' || echo '$(srcdir)/'`pair_ap/pair_homekit.c

pair_ap/lib_pair_ap_a-pair_homekit.obj: pair_ap/pair_homekit.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -MT pair_ap/lib_pair_ap_a-pair_homekit.obj -MD -MP -MF pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Tpo -c -o pair_ap/lib_pair_ap_a-pair_homekit.obj `if test -f 'pair_ap/pair_homekit.c'; then $(CYGPATH_W) 'pair_ap/pair_homekit.c'; else $(CYGPATH_W) '$(srcdir)/pair_ap/pair_homekit.c'; fi`
	$(AM_V_at)$(am__mv) pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Tpo pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Po
#	$(AM_V_CC)source='pair_ap/pair_homekit.c' object='pair_ap/lib_pair_ap_a-pair_homekit.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -c -o pair_ap/lib_pair_ap_a-pair_homekit.obj `if test -f 'pair_ap/pair_homekit.c'; then $(CYGPATH_W) 'pair_ap/pair_homekit.c'; else $(CYGPATH_W) '$(srcdir)/pair_ap/pair_homekit.c'; fi`

pair_ap/lib_pair_ap_a-pair-tlv.o: pair_ap/pair-tlv.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -MT pair_ap/lib_pair_ap_a-pair-tlv.o -MD -MP -MF pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Tpo -c -o pair_ap/lib_pair_ap_a-pair-tlv.o `test -f 'pair_ap/pair-tlv.c' || echo '$(srcdir)/'`pair_ap/pair-tlv.c
	$(AM_V_at)$(am__mv) pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Tpo pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Po
#	$(AM_V_CC)source='pair_ap/pair-tlv.c' object='pair_ap/lib_pair_ap_a-pair-tlv.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -c -o pair_ap/lib_pair_ap_a-pair-tlv.o `test -f 'pair_ap/pair-tlv.c' || echo '$(srcdir)/'`pair_ap/pair-tlv.c

pair_ap/lib_pair_ap_a-pair-tlv.obj: pair_ap/pair-tlv.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -MT pair_ap/lib_pair_ap_a-pair-tlv.obj -MD -MP -MF pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Tpo -c -o pair_ap/lib_pair_ap_a-pair-tlv.obj `if test -f 'pair_ap/pair-tlv.c'; then $(CYGPATH_W) 'pair_ap/pair-tlv.c'; else $(CYGPATH_W) '$(srcdir)/pair_ap/pair-tlv.c'; fi`
	$(AM_V_at)$(am__mv) pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Tpo pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Po
#	$(AM_V_CC)source='pair_ap/pair-tlv.c' object='pair_ap/lib_pair_ap_a-pair-tlv.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_pair_ap_a_CFLAGS) $(CFLAGS) -c -o pair_ap/lib_pair_ap_a-pair-tlv.obj `if test -f 'pair_ap/pair-tlv.c'; then $(CYGPATH_W) 'pair_ap/pair-tlv.c'; else $(CYGPATH_W) '$(srcdir)/pair_ap/pair-tlv.c'; fi`

tinyhttp/lib_tinyhttp_a-chunk.o: tinyhttp/chunk.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -MT tinyhttp/lib_tinyhttp_a-chunk.o -MD -MP -MF tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Tpo -c -o tinyhttp/lib_tinyhttp_a-chunk.o `test -f 'tinyhttp/chunk.c' || echo '$(srcdir)/'`tinyhttp/chunk.c
	$(AM_V_at)$(am__mv) tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Tpo tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Po
#	$(AM_V_CC)source='tinyhttp/chunk.c' object='tinyhttp/lib_tinyhttp_a-chunk.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -c -o tinyhttp/lib_tinyhttp_a-chunk.o `test -f 'tinyhttp/chunk.c' || echo '$(srcdir)/'`tinyhttp/chunk.c

tinyhttp/lib_tinyhttp_a-chunk.obj: tinyhttp/chunk.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -MT tinyhttp/lib_tinyhttp_a-chunk.obj -MD -MP -MF tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Tpo -c -o tinyhttp/lib_tinyhttp_a-chunk.obj `if test -f 'tinyhttp/chunk.c'; then $(CYGPATH_W) 'tinyhttp/chunk.c'; else $(CYGPATH_W) '$(srcdir)/tinyhttp/chunk.c'; fi`
	$(AM_V_at)$(am__mv) tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Tpo tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Po
#	$(AM_V_CC)source='tinyhttp/chunk.c' object='tinyhttp/lib_tinyhttp_a-chunk.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -c -o tinyhttp/lib_tinyhttp_a-chunk.obj `if test -f 'tinyhttp/chunk.c'; then $(CYGPATH_W) 'tinyhttp/chunk.c'; else $(CYGPATH_W) '$(srcdir)/tinyhttp/chunk.c'; fi`

tinyhttp/lib_tinyhttp_a-header.o: tinyhttp/header.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -MT tinyhttp/lib_tinyhttp_a-header.o -MD -MP -MF tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Tpo -c -o tinyhttp/lib_tinyhttp_a-header.o `test -f 'tinyhttp/header.c' || echo '$(srcdir)/'`tinyhttp/header.c
	$(AM_V_at)$(am__mv) tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Tpo tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Po
#	$(AM_V_CC)source='tinyhttp/header.c' object='tinyhttp/lib_tinyhttp_a-header.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -c -o tinyhttp/lib_tinyhttp_a-header.o `test -f 'tinyhttp/header.c' || echo '$(srcdir)/'`tinyhttp/header.c

tinyhttp/lib_tinyhttp_a-header.obj: tinyhttp/header.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -MT tinyhttp/lib_tinyhttp_a-header.obj -MD -MP -MF tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Tpo -c -o tinyhttp/lib_tinyhttp_a-header.obj `if test -f 'tinyhttp/header.c'; then $(CYGPATH_W) 'tinyhttp/header.c'; else $(CYGPATH_W) '$(srcdir)/tinyhttp/header.c'; fi`
	$(AM_V_at)$(am__mv) tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Tpo tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Po
#	$(AM_V_CC)source='tinyhttp/header.c' object='tinyhttp/lib_tinyhttp_a-header.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -c -o tinyhttp/lib_tinyhttp_a-header.obj `if test -f 'tinyhttp/header.c'; then $(CYGPATH_W) 'tinyhttp/header.c'; else $(CYGPATH_W) '$(srcdir)/tinyhttp/header.c'; fi`

tinyhttp/lib_tinyhttp_a-http.o: tinyhttp/http.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -MT tinyhttp/lib_tinyhttp_a-http.o -MD -MP -MF tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Tpo -c -o tinyhttp/lib_tinyhttp_a-http.o `test -f 'tinyhttp/http.c' || echo '$(srcdir)/'`tinyhttp/http.c
	$(AM_V_at)$(am__mv) tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Tpo tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Po
#	$(AM_V_CC)source='tinyhttp/http.c' object='tinyhttp/lib_tinyhttp_a-http.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -c -o tinyhttp/lib_tinyhttp_a-http.o `test -f 'tinyhttp/http.c' || echo '$(srcdir)/'`tinyhttp/http.c

tinyhttp/lib_tinyhttp_a-http.obj: tinyhttp/http.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -MT tinyhttp/lib_tinyhttp_a-http.obj -MD -MP -MF tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Tpo -c -o tinyhttp/lib_tinyhttp_a-http.obj `if test -f 'tinyhttp/http.c'; then $(CYGPATH_W) 'tinyhttp/http.c'; else $(CYGPATH_W) '$(srcdir)/tinyhttp/http.c'; fi`
	$(AM_V_at)$(am__mv) tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Tpo tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Po
#	$(AM_V_CC)source='tinyhttp/http.c' object='tinyhttp/lib_tinyhttp_a-http.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_tinyhttp_a_CFLAGS) $(CFLAGS) -c -o tinyhttp/lib_tinyhttp_a-http.obj `if test -f 'tinyhttp/http.c'; then $(CYGPATH_W) 'tinyhttp/http.c'; else $(CYGPATH_W) '$(srcdir)/tinyhttp/http.c'; fi`

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`
install-man1: $(man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(man_MANS)'; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(PROGRAMS) $(LIBRARIES) $(MANS) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f FFTConvolver/$(DEPDIR)/$(am__dirstamp)
	-rm -f FFTConvolver/$(am__dirstamp)
	-rm -f pair_ap/$(DEPDIR)/$(am__dirstamp)
	-rm -f pair_ap/$(am__dirstamp)
	-rm -f tinyhttp/$(DEPDIR)/$(am__dirstamp)
	-rm -f tinyhttp/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
#install-exec-hook:
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-noinstLIBRARIES \
	clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f ./$(DEPDIR)/activity_monitor.Po
	-rm -f ./$(DEPDIR)/alac.Po
	-rm -f ./$(DEPDIR)/apple_alac.Po
	-rm -f ./$(DEPDIR)/audio.Po
	-rm -f ./$(DEPDIR)/audio_alsa.Po
	-rm -f ./$(DEPDIR)/audio_ao.Po
	-rm -f ./$(DEPDIR)/audio_dummy.Po
	-rm -f ./$(DEPDIR)/audio_jack.Po
	-rm -f ./$(DEPDIR)/audio_pa.Po
	-rm -f ./$(DEPDIR)/audio_pipe.Po
	-rm -f ./$(DEPDIR)/audio_pw.Po
	-rm -f ./$(DEPDIR)/audio_sndio.Po
	-rm -f ./$(DEPDIR)/audio_soundio.Po
	-rm -f ./$(DEPDIR)/audio_stdout.Po
	-rm -f ./$(DEPDIR)/common.Po
	-rm -f ./$(DEPDIR)/dacp.Po
	-rm -f ./$(DEPDIR)/dbus-service.Po
	-rm -f ./$(DEPDIR)/gitversion.Po
	-rm -f ./$(DEPDIR)/lib_dbus_interface_a-dbus-interface.Po
	-rm -f ./$(DEPDIR)/lib_mpris_interface_a-mpris-interface.Po
	-rm -f ./$(DEPDIR)/loudness.Po
	-rm -f ./$(DEPDIR)/mdns.Po
	-rm -f ./$(DEPDIR)/mdns_avahi.Po
	-rm -f ./$(DEPDIR)/mdns_dns_sd.Po
	-rm -f ./$(DEPDIR)/mdns_external.Po
	-rm -f ./$(DEPDIR)/mdns_tinysvcmdns.Po
	-rm -f ./$(DEPDIR)/metadata_hub.Po
	-rm -f ./$(DEPDIR)/mpris-service.Po
	-rm -f ./$(DEPDIR)/mqtt.Po
	-rm -f ./$(DEPDIR)/player.Po
	-rm -f ./$(DEPDIR)/plist_xml_strings.Po
	-rm -f ./$(DEPDIR)/ptp-utilities.Po
	-rm -f ./$(DEPDIR)/rtp.Po
	-rm -f ./$(DEPDIR)/rtsp.Po
	-rm -f ./$(DEPDIR)/shairport-sync-dbus-test-client.Po
	-rm -f ./$(DEPDIR)/shairport-sync-mpris-test-client.Po
	-rm -f ./$(DEPDIR)/shairport.Po
	-rm -f ./$(DEPDIR)/tinysvcmdns.Po
	-rm -f FFTConvolver/$(DEPDIR)/AudioFFT.Po
	-rm -f FFTConvolver/$(DEPDIR)/FFTConvolver.Po
	-rm -f FFTConvolver/$(DEPDIR)/Utilities.Po
	-rm -f FFTConvolver/$(DEPDIR)/convolver.Po
	-rm -f pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Po
	-rm -f pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Po
	-rm -f pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Po
	-rm -f pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Po
	-rm -f tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Po
	-rm -f tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Po
	-rm -f tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-man

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man1

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f ./$(DEPDIR)/activity_monitor.Po
	-rm -f ./$(DEPDIR)/alac.Po
	-rm -f ./$(DEPDIR)/apple_alac.Po
	-rm -f ./$(DEPDIR)/audio.Po
	-rm -f ./$(DEPDIR)/audio_alsa.Po
	-rm -f ./$(DEPDIR)/audio_ao.Po
	-rm -f ./$(DEPDIR)/audio_dummy.Po
	-rm -f ./$(DEPDIR)/audio_jack.Po
	-rm -f ./$(DEPDIR)/audio_pa.Po
	-rm -f ./$(DEPDIR)/audio_pipe.Po
	-rm -f ./$(DEPDIR)/audio_pw.Po
	-rm -f ./$(DEPDIR)/audio_sndio.Po
	-rm -f ./$(DEPDIR)/audio_soundio.Po
	-rm -f ./$(DEPDIR)/audio_stdout.Po
	-rm -f ./$(DEPDIR)/common.Po
	-rm -f ./$(DEPDIR)/dacp.Po
	-rm -f ./$(DEPDIR)/dbus-service.Po
	-rm -f ./$(DEPDIR)/gitversion.Po
	-rm -f ./$(DEPDIR)/lib_dbus_interface_a-dbus-interface.Po
	-rm -f ./$(DEPDIR)/lib_mpris_interface_a-mpris-interface.Po
	-rm -f ./$(DEPDIR)/loudness.Po
	-rm -f ./$(DEPDIR)/mdns.Po
	-rm -f ./$(DEPDIR)/mdns_avahi.Po
	-rm -f ./$(DEPDIR)/mdns_dns_sd.Po
	-rm -f ./$(DEPDIR)/mdns_external.Po
	-rm -f ./$(DEPDIR)/mdns_tinysvcmdns.Po
	-rm -f ./$(DEPDIR)/metadata_hub.Po
	-rm -f ./$(DEPDIR)/mpris-service.Po
	-rm -f ./$(DEPDIR)/mqtt.Po
	-rm -f ./$(DEPDIR)/player.Po
	-rm -f ./$(DEPDIR)/plist_xml_strings.Po
	-rm -f ./$(DEPDIR)/ptp-utilities.Po
	-rm -f ./$(DEPDIR)/rtp.Po
	-rm -f ./$(DEPDIR)/rtsp.Po
	-rm -f ./$(DEPDIR)/shairport-sync-dbus-test-client.Po
	-rm -f ./$(DEPDIR)/shairport-sync-mpris-test-client.Po
	-rm -f ./$(DEPDIR)/shairport.Po
	-rm -f ./$(DEPDIR)/tinysvcmdns.Po
	-rm -f FFTConvolver/$(DEPDIR)/AudioFFT.Po
	-rm -f FFTConvolver/$(DEPDIR)/FFTConvolver.Po
	-rm -f FFTConvolver/$(DEPDIR)/Utilities.Po
	-rm -f FFTConvolver/$(DEPDIR)/convolver.Po
	-rm -f pair_ap/$(DEPDIR)/lib_pair_ap_a-pair-tlv.Po
	-rm -f pair_ap/$(DEPDIR)/lib_pair_ap_a-pair.Po
	-rm -f pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_fruit.Po
	-rm -f pair_ap/$(DEPDIR)/lib_pair_ap_a-pair_homekit.Po
	-rm -f tinyhttp/$(DEPDIR)/lib_tinyhttp_a-chunk.Po
	-rm -f tinyhttp/$(DEPDIR)/lib_tinyhttp_a-header.Po
	-rm -f tinyhttp/$(DEPDIR)/lib_tinyhttp_a-http.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-man

uninstall-man: uninstall-man1

.MAKE: all check install install-am install-exec-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	clean-noinstLIBRARIES clean-noinstPROGRAMS cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-exec-hook install-html install-html-am \
	install-info install-info-am install-man install-man1 \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-man uninstall-man1

.PRECIOUS: Makefile

gitversion.h: .git/index
	printf "// Do not edit!\n" > gitversion.h
	printf "// This file is automatically generated by 'git describe --tags --dirty --broken', if available.\n" >> gitversion.h
	printf "  char git_version_string[] = \"" >> gitversion.h
	git describe --tags --dirty --broken | tr -d '[[:space:]]' >> gitversion.h
	printf "\";\n" >> gitversion.h
gitversion.c: gitversion.h
	touch gitversion.c
plist_xml_strings.h: plists/get_info_response.xml
	printf "// Do not edit!\n" > plist_xml_strings.h
	printf "// This file is automatically generated from files in the plists folder.\n\n" >> plist_xml_strings.h
	xxd -i $(top_srcdir)/plists/get_info_response.xml - | sed -e 's/[^ ]*plists_get_info_response_xml/plists_get_info_response_xml/g' >> plist_xml_strings.h
	printf "\n" >> plist_xml_strings.h
plist_xml_strings.c: plist_xml_strings.h
	touch plist_xml_strings.c

dbus-interface.c:  org.gnome.ShairportSync.xml
	gdbus-codegen --interface-prefix org.gnome --generate-c-code dbus-interface $(top_srcdir)/org.gnome.ShairportSync.xml
dbus-interface.h: dbus-interface.c
	touch dbus-interface.h

mpris-interface.c:  org.mpris.MediaPlayer2.xml
	gdbus-codegen --interface-prefix org.mpris --generate-c-code mpris-interface $(top_srcdir)/org.mpris.MediaPlayer2.xml
mpris-interface.h: mpris-interface.c
	touch mpris-interface.h

 #Make it, but don't install it anywhere

 #Make it, but don't install it anywhere
$(CONFIG_FILE_INSTALL_TARGET): scripts/shairport-sync.conf
	install -d $(DESTDIR)$(sysconfdir)
	install -m 0644 $(top_srcdir)/scripts/shairport-sync.conf $(DESTDIR)$(sysconfdir)/shairport-sync.conf.sample
	[ -f $(DESTDIR)$(sysconfdir)/shairport-sync.conf ] || cp $(top_srcdir)/scripts/shairport-sync.conf $(DESTDIR)$(sysconfdir)/shairport-sync.conf

$(DBUS_POLICY_INSTALL_TARGET): $(DBUS_POLICY_FILE)
	install -d $(DESTDIR)$(DBUS_POLICY_DIR)
	install -m 0644 $(top_srcdir)/$(DBUS_POLICY_FILE) $(DESTDIR)$(DBUS_POLICY_DIR)/shairport-sync-dbus.conf

$(MPRIS_POLICY_INSTALL_TARGET): $(MPRIS_POLICY_FILE)
	install -d $(DESTDIR)$(DBUS_POLICY_DIR)
	install -m 0644 $(top_srcdir)/$(MPRIS_POLICY_FILE) $(DESTDIR)$(DBUS_POLICY_DIR)/shairport-sync-mpris.conf

$(INSTALL_GROUP_TARGET):
	getent group shairport-sync &>/dev/null || groupadd -r shairport-sync &>/dev/null

$(INSTALL_USER_TARGET): $(INSTALL_GROUP_TARGET)
	getent passwd shairport-sync &>/dev/null || useradd -r -M -g shairport-sync -s /usr/sbin/nologin -G audio shairport-sync &>/dev/null

# watch out -- shairport-sync is created during the ./configure step and
# will be stored in a scripts folder in the _build_ folder
# which will be the source folder if you're not using a separate build folder

#$(INSTALL_SYSTEMV_TARGET): scripts/shairport-sync $(INSTALL_USER_TARGET)
#	install -d $(DESTDIR)$(sysconfdir)/init.d
#	[ -e $(DESTDIR)$(sysconfdir)/init.d/shairport-sync ] || install -m 0755 scripts/shairport-sync $(DESTDIR)$(sysconfdir)/init.d

# watch out -- shairport-sync.service is created during the ./configure step and
# will be stored in a scripts folder in the _build_ folder
# which will be the source folder if you're not using a separate build folder

$(INSTALL_SYSTEMD_TARGET): scripts/$(SYSTEMD_SERVICE) $(INSTALL_USER_TARGET)
	install -d $(DESTDIR)$(systemdsystemunitdir)
	[ -e $(DESTDIR)$(systemdsystemunitdir)/shairport-sync.service ] || install -m 0644 scripts/$(SYSTEMD_SERVICE) $(DESTDIR)$(systemdsystemunitdir)/shairport-sync.service

# Choose a uid and gid of 801 completely arbitrarity, except that it should be below 1000. FreeBSD doesn't seem to allow you to say "an ID in the range of..."
#install-freebsd-user-local:
#	pw showgroup shairport-sync > /dev/null 2>&1 || pw addgroup -n shairport-sync -g 801 > /dev/null 2>&1
#	pw showuser shairport-sync > /dev/null 2>&1 || pw adduser -c "shairport-sync unprivileged user" -n shairport-sync -u 801 -s /usr/sbin/nologin -d /nonexistent > /dev/null 2>&1

#$(INSTALL_FREEBSD_TARGET): scripts/shairport-sync.freebsd install-freebsd-user-local
#	install -d -o shairport-sync -g shairport-sync $(DESTDIR)/var/run/shairport-sync
#	install -d $(DESTDIR)/usr/local/etc/rc.d/
#	install -m 0555 $(top_srcdir)/scripts/shairport-sync.freebsd $(DESTDIR)/usr/local/etc/rc.d/shairport_sync

#$(INSTALL_CYGWIN_TARGET): scripts/shairport-sync-config
#	install -d $(DESTDIR)/usr/local/bin
#	[ -e $(DESTDIR)/usr/local/bin/shairport-sync-config ] || install -m 0755 $(top_srcdir)/scripts/shairport-sync-config $(DESTDIR)/usr/local/bin/

install-config-files: $(CONFIG_FILE_INSTALL_TARGET) \
                   $(DBUS_POLICY_INSTALL_TARGET) \
                   $(MPRIS_POLICY_INSTALL_TARGET) \
                   $(INSTALL_SYSTEMV_TARGET) \
                   $(INSTALL_SYSTEMD_TARGET) \
                   $(INSTALL_FREEBSD_TARGET) \
                   $(INSTALL_CYGWIN_TARGET)

install-exec-hook: install-config-files

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
